### ISSUE TITLE
Newer version support

### ISSUE THREAD

**Issue by maxmadknight** [cwoodrgr/scout-aws-elastic#1]
Can you please add support for a newer version of babenkoivan/scout-elasticsearch-driver
Currently, your package is locked on 4.0.3, I have used ^4.2

**Comment by cwoodrgr** [comment]
Sorry for the late response. I do need to update the project and will work to update the dependency as well.

**Comment by cwoodrgr** [comment]
The dependencies have been updated, you should now be able to use the version you requested.
